[versions]
agp = "9.4.1"
compileSdk = "37"
minSdk = "21"
appcompat = "1.7.1"
core = "1.16.0"
palette = "1.0.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core", version.ref = "core" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
